### ISSUE TITLE
BC Break in 4.1.0

### ISSUE THREAD

**Issue by TomAdam** [Padam87/RasterizeBundle#26]
This commit (https://github.com/Padam87/RasterizeBundle/commit/a63df2af7dddc50377c0fbfb181c2f088f00b6c6) introduces a BC break when used with Symfony 3.4. An exception is thrown during container compilation:

```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\UndefinedMethodException: Attempted to call an undefined method named "getRootNode" of class "Symfony\Component\Config\Definition\Builder\TreeBuilder". in vendor/padam87/rasterize-bundle/DependencyInjection/Configuration.php:18
```

`Treebuilder::getRootNode()` does not exist in 3.4 versions of Symfony. This lead me to notice that there are no composer dependencies for `symfony/config`, `symfony/dependency-injection` or `symfony/http-kernel`, all of which are used within the bundle.

I suggest one of two paths:

1. Roll back the change and release a patch version. Reapply, add a minimum Symfony version of 4 on the above dependencies and release a new major version of the bundle.

2. Add a patch that only uses `getRootNode` if it is available, add dependencies on the above components and release a patch version.

I'm happy to put together a PR for these or other approach, let me know what you think.

**Comment by Padam87** [comment]
The dependencies are not there, because technically this package is not dependent on any of those.
Back when I started this I set it up specifically with usage outside of symfony in mind, because I needed it for both.

I could just set it manually and it worked fine.
```php
$config = new ConfigHelper('./', [...]);
$rasterizer = new Rasterizer($config);
```

This is besides the point, just some history. :)

Anyway, since the DI related dependencies are not marked a conflict should have been added. For now I would say option 2 is okay, and the next major will mark the DI dependencies. Since the project lost a lot of weight over the years, outside of symfony usage is not relevant anymore.

**Comment by TomAdam** [comment]
Makes sense. The conflict is a good idea to enforce the requirement without causing installation. If it is purely used as a bundle these days the normal approach is to depend on `symfony/framework-bundle`. Perhaps that would be a good route for the next major?

**Comment by Padam87** [comment]
Yeah, absolutely. Over time, the whole point of this bundle has became the symfony config, so I see no reason to keep it as universal.
